name: ai
services:
  ollama:
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: 1
    environment:
      OLLAMA_KEEP_ALIVE: 24h
    image: docker.io/ollama/ollama:latest
    networks:
      ollama-docker: null
    ports:
      - mode: ingress
        target: 11434
        published: "11434"
        protocol: tcp
    pull_policy: always
    restart: unless-stopped
    tty: true
    volumes:
      - ./data/ollama:/root/.ollama:rw

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data/searxng:/etc/searxng:rw
    environment:
      SEARXNG_HOSTNAME: localhost:8080/
    networks:
      ollama-docker: null
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  docling:
    container_name: docling
    image: quay.io/docling-project/docling-serve:latest
    ports:
      - "5001:5001"
    environment:
      DOCLING_SERVE_ENABLE_UI: true
    restart: unless-stopped
    networks:
      ollama-docker: null
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: 1

  open-webui:
    container_name: open-webui
    depends_on:
      ollama:
        condition: service_started
        required: true
    environment:
      ENV: dev
      OLLAMA_BASE_URLS: http://ollama:11434
      WEBUI_AUTH: "False"
      WEBUI_NAME: ai.corvin.cloud
      WEBUI_SECRET_KEY: t0p-s3cr3t
      WEBUI_URL: http://localhost:8080

      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
    image: ghcr.io/open-webui/open-webui:main
    networks:
      ollama-docker: null
    ports:
      - mode: ingress
        target: 8080
        published: "3000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - ./data/open-webui:/app/backend/data:rw

networks:
  ollama-docker:
    name: ai_ollama-docker
